/*
============================================================
Business Problem 1: Total Revenue
============================================================

Business Question:
What is the total revenue generated by the company?

*/

SELECT
    ROUND(SUM(s.quantity * p.unit_price_usd), 2) AS total_revenue_usd
FROM Sales AS s
INNER JOIN Products AS p
    ON s.product_key = p.product_key;



